/*
 * Created by v.bochechko on 04.12.2017.
 */
enum ScreenPicture {
    PASSWORD,
    INCORRECT_PASSWORD,
    AFTER_PASSWORD,

    MENU_REGISTRATION,
    WRONG_REG_NUMBER,

    REGISTRATION,
    REGISTRATION_FISCAL_MODE,
    GET_REGISTRATION_DATA_FROM_CABINET,
    EMPTY_SCREEN,
    RE_REGISTRATION_MENU,
    RE_REGISTRATION_MENU_NOT_AUTONOMIC,
    DOCUMENT_NOT_SENDED_SCREEN,
    TURN_OFF_CASHBOX,

    OPEN_SHIFT_MENU,
    SHIFT_MENU_OPEN_SHIFT,
    LESS_MONEY_IN_CASHBOX,
    FREE_SALE_MODE,
    NOT_ENOUGH_MONEY,
    FREE_SALE_MODE_CHANGE_400
}